server.port=8082
spring.application.name=user-service

# MYSQL DB CONFIG
spring.datasource.url=jdbc:mysql://localhost:3306/eventsphere_user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Pritam@1999
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# EUREKA CONFIG
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
eureka.instance.prefer-ip-address=true

# SWAGGER CONFIG
springdoc.api-docs.path=/api/users/v3/api-docs
